CREATE TABLE BRANCH (ID INTEGER PRIMARY KEY, BRANCH_NAME VARCHAR(64), ADDRESS VARCHAR(64), STATUS   BIT);

 CREATE TABLE USER (ID INTEGER PRIMARY KEY, FIRST_NAME VARCHAR(64), LAST_NAME VARCHAR(64), USERNAME VARCHAR(64)); 